apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: 022499028145.dkr.ecr.ap-southeast-1.amazonaws.com/microservice-converter:latest
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
      imagePullSecrets:
        - name: ap-southeast-1-ecr-registry